### Dataset

The dataset is the tweet archive of Twitter user @dog_rates, also known as WeRateDogs. WeRateDogs is a Twitter account that rates people's dogs with a humorous comment about the dog. These ratings almost always have a denominator of 10. The numerators, though? Almost always greater than 10. 11/10, 12/10, 13/10, etc. Why? Because "they're good dogs." WeRateDogs has over 4 million followers and has received international media coverage.


A csv file twitter_archive_enhanced contains basic tweet data of 2300+ tweets. Tweet likes and retweet counts will be gathered by querying Twitterâ€™s API using the tweet IDs from twitter_archive_enhanced. Image prediction, another dataset, will be downloaded from a url.

#### Import Libraries

In [1]:
import pandas as pd
import requests
import tweepy
import json
import time

In [2]:
twitter_archive = pd.read_csv('twitter-archive-enhanced.csv')
twitter_archive

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2351,666049248165822465,NaN,NaN,2015-11-16 00:24:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a 1949 1st generation vulpix. Enj...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666049248...,5,10,None,None,None,None,None
2352,666044226329800704,NaN,NaN,2015-11-16 00:04:52 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a purebred Piers Morgan. Loves to Netf...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666044226...,6,10,a,None,None,None,None
2353,666033412701032449,NaN,NaN,2015-11-15 23:21:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a very happy pup. Big fan of well-main...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666033412...,9,10,a,None,None,None,None
2354,666029285002620928,NaN,NaN,2015-11-15 23:05:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is a western brown Mitsubishi terrier. Up...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666029285...,7,10,a,None,None,None,None
2355,666020888022790149,NaN,NaN,2015-11-15 22:32:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have a Japanese Irish Setter. Lost eye...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666020888...,8,10,None,None,None,None,None

##### get dataset from url

In [3]:
#get image predictions from url
url = 'https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv'
response = requests.get(url)

In [4]:
#save file
with open('image-predictions.tsv', mode='wb') as file:
    file.write(response.content)

##### twitter API query

In [5]:
bearer_token = "AAAAAAAAAAAAAAAAAAAAAMTubAEAAAAAt8DO%2FsbSj3rNRqINqjBE0K%2FJyUg%3D6R2S7U6SKi7EM47AVx4PzTCA1JqXmBQX1ejZ2QSeF4BO5mzONp"

In [6]:
#bearer_token = 'XXXXXX'
client = tweepy.Client(bearer_token = bearer_token, wait_on_rate_limit = True)
tweet_ids = twitter_archive.tweet_id

In [7]:
tweet_fields = ['id', 'public_metrics', 'source']

start_time = time.time()

with open('tweet_json.txt', 'w') as file:
    for i in (tweet_ids):
        metrics = {}
        faulty_id = {}    
        tweet_a = client.get_tweet(id = i, tweet_fields = tweet_fields) 
        
        try:
            metrics = tweet_a.data.get('public_metrics')
            metrics['tweet_id'] = i
            metrics['source'] = tweet_a.data.get('source')
            json.dump(metrics, file)
            file.write('\n')       
            
        except AttributeError as a:
            pass
            
print(time.time() - start_time)

Rate limit exceeded. Sleeping for 803 seconds.
Rate limit exceeded. Sleeping for 699 seconds.
Rate limit exceeded. Sleeping for 713 seconds.
Rate limit exceeded. Sleeping for 797 seconds.
Rate limit exceeded. Sleeping for 822 seconds.
Rate limit exceeded. Sleeping for 822 seconds.
Rate limit exceeded. Sleeping for 834 seconds.

6360.176586151123

In [8]:
!git init

Initialized empty Git repository in C:/Users/User/Desktop/Data Science/git_data_wrangling/.git/

In [9]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	data_gatherimg.ipynb
	image-predictions.tsv
	tweet_json.txt
	twitter-archive-enhanced.csv

nothing added to commit but untracked files present (use "git add" to track)